(defpackage :llvm-runtime
  (:use #:cl)
  (:export #:define-llvm-function
           #:make-llvm-context
           ;; LLVM ops.
           #:add.i1
           #:add.i16
           #:add.i32
           #:add.i64
           #:add.i8
           #:alloca
           #:and.i1
           #:and.i16
           #:and.i32
           #:and.i64
           #:and.i8
           #:ashr.i1
           #:ashr.i16
           #:ashr.i32
           #:ashr.i64
           #:ashr.i8
           #:bitcast.f32.i32
           #:bitcast.f64.i64
           #:bitcast.i32.f32
           #:bitcast.i32.i32
           #:bitcast.i64.f64
           #:bitcast.i64.i64
           #:call-direct
           #:call-indirect
           #:fadd.f32
           #:fadd.f64
           #:fcmp.oeq.f32
           #:fcmp.oeq.f64
           #:fcmp.oeq.fused.f32
           #:fcmp.oeq.fused.f64
           #:fcmp.oge.f32
           #:fcmp.oge.f64
           #:fcmp.oge.fused.f32
           #:fcmp.oge.fused.f64
           #:fcmp.ogt.f32
           #:fcmp.ogt.f64
           #:fcmp.ogt.fused.f32
           #:fcmp.ogt.fused.f64
           #:fcmp.ole.f32
           #:fcmp.ole.f64
           #:fcmp.ole.fused.f32
           #:fcmp.ole.fused.f64
           #:fcmp.olt.f32
           #:fcmp.olt.f64
           #:fcmp.olt.fused.f32
           #:fcmp.olt.fused.f64
           #:fcmp.one.f32
           #:fcmp.one.f64
           #:fcmp.one.fused.f32
           #:fcmp.one.fused.f64
           #:fcmp.ueq.f32
           #:fcmp.ueq.f64
           #:fcmp.ueq.fused.f32
           #:fcmp.ueq.fused.f64
           #:fcmp.uge.f32
           #:fcmp.uge.f64
           #:fcmp.uge.fused.f32
           #:fcmp.uge.fused.f64
           #:fcmp.ugt.f32
           #:fcmp.ugt.f64
           #:fcmp.ugt.fused.f32
           #:fcmp.ugt.fused.f64
           #:fcmp.ule.f32
           #:fcmp.ule.f64
           #:fcmp.ule.fused.f32
           #:fcmp.ule.fused.f64
           #:fcmp.ult.f32
           #:fcmp.ult.f64
           #:fcmp.ult.fused.f32
           #:fcmp.ult.fused.f64
           #:fcmp.une.f32
           #:fcmp.une.f64
           #:fcmp.une.fused.f32
           #:fcmp.une.fused.f64
           #:fdiv.f32
           #:fdiv.f64
           #:fmul.f32
           #:fmul.f64
           #:fpext.f32.f32
           #:fpext.f32.f64
           #:fpext.f64.f64
           #:fptosi.f32.i1
           #:fptosi.f32.i16
           #:fptosi.f32.i32
           #:fptosi.f32.i64
           #:fptosi.f32.i8
           #:fptosi.f64.i1
           #:fptosi.f64.i16
           #:fptosi.f64.i32
           #:fptosi.f64.i64
           #:fptosi.f64.i8
           #:fptoui.f32.i1
           #:fptoui.f32.i16
           #:fptoui.f32.i32
           #:fptoui.f32.i64
           #:fptoui.f32.i8
           #:fptoui.f64.i1
           #:fptoui.f64.i16
           #:fptoui.f64.i32
           #:fptoui.f64.i64
           #:fptoui.f64.i8
           #:fptrunc.f32.f32
           #:fptrunc.f64.f32
           #:fptrunc.f64.f64
           #:frem.f32
           #:frem.f64
           #:fsub.f32
           #:fsub.f64
           #:icmp.eq.fused.i1
           #:icmp.eq.fused.i16
           #:icmp.eq.fused.i32
           #:icmp.eq.fused.i64
           #:icmp.eq.fused.i8
           #:icmp.eq.i1
           #:icmp.eq.i16
           #:icmp.eq.i32
           #:icmp.eq.i64
           #:icmp.eq.i8
           #:icmp.ne.fused.i1
           #:icmp.ne.fused.i16
           #:icmp.ne.fused.i32
           #:icmp.ne.fused.i64
           #:icmp.ne.fused.i8
           #:icmp.ne.i1
           #:icmp.ne.i16
           #:icmp.ne.i32
           #:icmp.ne.i64
           #:icmp.ne.i8
           #:icmp.sge.fused.i1
           #:icmp.sge.fused.i16
           #:icmp.sge.fused.i32
           #:icmp.sge.fused.i64
           #:icmp.sge.fused.i8
           #:icmp.sge.i1
           #:icmp.sge.i16
           #:icmp.sge.i32
           #:icmp.sge.i64
           #:icmp.sge.i8
           #:icmp.sgt.fused.i1
           #:icmp.sgt.fused.i16
           #:icmp.sgt.fused.i32
           #:icmp.sgt.fused.i64
           #:icmp.sgt.fused.i8
           #:icmp.sgt.i1
           #:icmp.sgt.i12
           #:icmp.sgt.i16
           #:icmp.sgt.i32
           #:icmp.sgt.i64
           #:icmp.sgt.i8
           #:icmp.sle.fused.i1
           #:icmp.sle.fused.i16
           #:icmp.sle.fused.i32
           #:icmp.sle.fused.i64
           #:icmp.sle.fused.i8
           #:icmp.sle.i1
           #:icmp.sle.i16
           #:icmp.sle.i32
           #:icmp.sle.i64
           #:icmp.sle.i8
           #:icmp.slt.fused.i1
           #:icmp.slt.fused.i16
           #:icmp.slt.fused.i32
           #:icmp.slt.fused.i64
           #:icmp.slt.fused.i8
           #:icmp.slt.i1
           #:icmp.slt.i16
           #:icmp.slt.i32
           #:icmp.slt.i64
           #:icmp.slt.i8
           #:icmp.uge.fused.i1
           #:icmp.uge.fused.i16
           #:icmp.uge.fused.i32
           #:icmp.uge.fused.i64
           #:icmp.uge.fused.i8
           #:icmp.uge.i1
           #:icmp.uge.i16
           #:icmp.uge.i32
           #:icmp.uge.i64
           #:icmp.uge.i8
           #:icmp.ugt.fused.i1
           #:icmp.ugt.fused.i16
           #:icmp.ugt.fused.i32
           #:icmp.ugt.fused.i64
           #:icmp.ugt.fused.i8
           #:icmp.ugt.i1
           #:icmp.ugt.i16
           #:icmp.ugt.i32
           #:icmp.ugt.i64
           #:icmp.ugt.i8
           #:icmp.ule.fused.i1
           #:icmp.ule.fused.i16
           #:icmp.ule.fused.i32
           #:icmp.ule.fused.i64
           #:icmp.ule.fused.i8
           #:icmp.ule.i1
           #:icmp.ule.i16
           #:icmp.ule.i32
           #:icmp.ule.i64
           #:icmp.ule.i8
           #:icmp.ult.fused.i1
           #:icmp.ult.fused.i16
           #:icmp.ult.fused.i32
           #:icmp.ult.fused.i64
           #:icmp.ult.fused.i8
           #:icmp.ult.i1
           #:icmp.ult.i16
           #:icmp.ult.i32
           #:icmp.ult.i64
           #:icmp.ult.i8
           #:load.f32
           #:load.f64
           #:load.i16
           #:load.i32
           #:load.i64
           #:load.i8
           #:lshr.i1
           #:lshr.i16
           #:lshr.i32
           #:lshr.i64
           #:lshr.i8
           #:mul.i1
           #:mul.i16
           #:mul.i32
           #:mul.i64
           #:mul.i8
           #:or.i1
           #:or.i16
           #:or.i32
           #:or.i64
           #:or.i8
           #:sdiv.i1
           #:sdiv.i16
           #:sdiv.i32
           #:sdiv.i64
           #:sdiv.i8
           #:select
           #:setjmp.prepare
           #:sext.i1.i1
           #:sext.i1.i16
           #:sext.i1.i32
           #:sext.i1.i64
           #:sext.i1.i8
           #:sext.i16.i1
           #:sext.i16.i16
           #:sext.i16.i32
           #:sext.i16.i64
           #:sext.i16.i8
           #:sext.i32.i1
           #:sext.i32.i16
           #:sext.i32.i32
           #:sext.i32.i64
           #:sext.i32.i8
           #:sext.i64.i1
           #:sext.i64.i16
           #:sext.i64.i32
           #:sext.i64.i64
           #:sext.i64.i8
           #:sext.i8.i1
           #:sext.i8.i16
           #:sext.i8.i32
           #:sext.i8.i64
           #:sext.i8.i8
           #:shl.i1
           #:shl.i16
           #:shl.i32
           #:shl.i64
           #:shl.i8
           #:sitofp.i1.f32
           #:sitofp.i1.f64
           #:sitofp.i16.f32
           #:sitofp.i16.f64
           #:sitofp.i32.f32
           #:sitofp.i32.f64
           #:sitofp.i64.f32
           #:sitofp.i64.f64
           #:sitofp.i8.f32
           #:sitofp.i8.f64
           #:srem.i1
           #:srem.i16
           #:srem.i32
           #:srem.i64
           #:srem.i8
           #:store.f32
           #:store.f64
           #:store.i16
           #:store.i32
           #:store.i64
           #:store.i8
           #:sub.i1
           #:sub.i16
           #:sub.i32
           #:sub.i64
           #:sub.i8
           #:trunc.i1.i1
           #:trunc.i1.i16
           #:trunc.i1.i32
           #:trunc.i1.i64
           #:trunc.i1.i8
           #:trunc.i16.i1
           #:trunc.i16.i16
           #:trunc.i16.i32
           #:trunc.i16.i64
           #:trunc.i16.i8
           #:trunc.i32.i1
           #:trunc.i32.i12
           #:trunc.i32.i16
           #:trunc.i32.i32
           #:trunc.i32.i64
           #:trunc.i32.i8
           #:trunc.i64.i1
           #:trunc.i64.i16
           #:trunc.i64.i32
           #:trunc.i64.i64
           #:trunc.i64.i8
           #:trunc.i8.i1
           #:trunc.i8.i16
           #:trunc.i8.i32
           #:trunc.i8.i64
           #:trunc.i8.i8
           #:udiv.i1
           #:udiv.i16
           #:udiv.i32
           #:udiv.i64
           #:udiv.i8
           #:uitofp.i1.f32
           #:uitofp.i1.f64
           #:uitofp.i16.f32
           #:uitofp.i16.f64
           #:uitofp.i32.f32
           #:uitofp.i32.f64
           #:uitofp.i64.f32
           #:uitofp.i64.f64
           #:uitofp.i8.f32
           #:uitofp.i8.f64
           #:urem.i1
           #:urem.i16
           #:urem.i32
           #:urem.i64
           #:urem.i8
           #:xor.i1
           #:xor.i16
           #:xor.i32
           #:xor.i64
           #:xor.i8
           #:zext.i1.i1
           #:zext.i1.i16
           #:zext.i1.i32
           #:zext.i1.i64
           #:zext.i1.i8
           #:zext.i16.i1
           #:zext.i16.i16
           #:zext.i16.i32
           #:zext.i16.i64
           #:zext.i16.i8
           #:zext.i32.i1
           #:zext.i32.i16
           #:zext.i32.i32
           #:zext.i32.i64
           #:zext.i32.i8
           #:zext.i64.i1
           #:zext.i64.i16
           #:zext.i64.i32
           #:zext.i64.i64
           #:zext.i64.i8
           #:zext.i8.i1
           #:zext.i8.i16
           #:zext.i8.i32
           #:zext.i8.i64
           #:zext.i8.i8
           ;; C support functions.
           #:read-c-string
           #:main
           #:main-1
           #:|_exit|
           #:|access|
           #:|close|
           #:|fstat|
           #:|gettimeofday|
           #:|isatty|
           #:|llvm.bswap.i32|
           #:|llvm.flt.rounds|
           #:|llvm.lifetime.end|
           #:|llvm.lifetime.start|
           #:|llvm.memcpy.p0i8.p0i8.i32|
           #:|llvm.memmove.p0i8.p0i8.i32|
           #:|llvm.memset.p0i8.i32|
           #:|llvm.memset.p0i8.i64|
	   #:|llvm.memcpy.p0i8.p0i8.i64|
	   #:|llvm.bswap.i32|
	   #:|llvm.ctlz.i32|
           #:|longjmp|
           #:|lseek|
           #:|mkdir|
           #:|nanosleep|
	   #:|usleep|
           #:|open|
           #:|read|
           #:|sbrk|
           #:|setjmp|
           #:|write|
	   #:|link|
           ;; SDL support functions.
           #:|_iota_video_init|
           #:|_iota_video_quit|
           #:|_iota_set_video_mode|
           #:|_iota_video_update|
           #:|_iota_poll_event|
           #:|_iota_grab_input|
           #:|_iota_warp_cursor|
           #:|_iota_show_cursor|
           #:|_iota_set_caption|
))
